base.init: Drop into an emergency shell if mounting the test image fails
Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/libs/base.init b/libs/base.init
--- a/libs/base.init
+++ b/libs/base.init
@@ -131,7 +131,11 @@ cat <<EOF >>/etc/fstab
 LABEL=test  /test  iso9660  defaults  0  0
 EOF
 mkdir /test
-mount -a
+if ! mount -a ; then
+	echo "Failed to mount test image, dropping into an emergency shell"
+	bash
+	exit
+fi
 
 # Check the presence of the test list and test env files
 if ! [ -e "/test/tests" ] || ! [ -e "/test/tests.env" ] ; then
